version: "2"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile

    ports:
    - "8080:80"
    volumes:
    - .:/var/www/public
    depends_on:
    - db
  db: 
    image: mysql:5.7
    environment:
    - MYSQL_HOST=db
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bamboo
    volumes: 
    - ./database:/var/lib/mysql
